### ISSUE TITLE
Only named exports can use 'export type' error

### ISSUE THREAD

**Issue by EmilIvanov** [samchungy/zod-openapi#105]
Hi, I'm getting this on the latest version:
```
node_modules/zod-openapi/lib-types/index.d.ts:3:1 - error TS1383: Only named exports may use 'export type'.

3 export type * from './openapi3-ts/dist';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error in node_modules/zod-openapi/lib-types/index.d.ts:3
```

TypeScript doesn't like the `export type *`

**Comment by samchungy** [comment]
Interesting @EmilIvanov , what version of Typescript are you running?

**Comment by EmilIvanov** [comment]
@samchungy  4.9.5

**Comment by samchungy** [comment]
I see I see, looks like they added it in 5.0.

https://github.com/microsoft/TypeScript/pull/52217

Hmmm let me see if there's something else I can do then. I may make this a breaking change in future versions

**Comment by EmilIvanov** [comment]
@samchungy I guess, I should add that I have TS configured like so `"skipLibCheck": false,`, in order to validate some `d.ts` files in the project. This wouldn't be a problem otherwise.
