### ISSUE TITLE
Support Tuples

### ISSUE THREAD

**Issue by ben-moo** [samchungy/zod-openapi#168]
Currently, when generating an OpenAPI schema from a fixed length Zod tuple, the tuple is transformed into an array of constrained length, but without a fixed order of elements.

This means that the generated schema will incorrectly reflect a valid schema given an array whose types are out of the order expected by the Zod tuple (e.g. `[string, number, boolean]` rather than `[number, string, boolean]`).

The expectation is that each element of a fixed-length tuple should be of a fixed type.

Example:

**Input**
```ts
const myTuple = z.tuple([z.number(), z.string(), z.boolean()]).openapi({ title: 'MyTuple' })
```

**Output**
```json
{
  "MyTuple": {
    "type": "array",
    "maxItems": 3,
    "minItems": 3,
    "items": {
      "oneOf": [
        {
          "type": "number"
        },
        {
          "type": "string"
        },
        {
          "type": "boolean"
        }
      ]
    },
    "title": "MyTuple"
}
```

**Expected - JSON Schema < 2020-12**
```json
{
  "MyTuple": {
    "type": "array",
    "items": [
      {
        "type": "number"
      },
      {
        "type": "string"
      },
      {
        "type": "boolean"
      }
    ],
    "additionalItems": false,
    "title": "MyTuple"
  }
}
```

**Expected - JSON Schema > 2020-12**
```json
{
  "MyTuple": {
    "type": "array",
    "prefixItems": [
      {
        "type": "number"
      },
      {
        "type": "string"
      },
      {
        "type": "boolean"
      }
    ],
    "items": false,
    "title": "MyTuple"
  }
}
```

**Comment by samchungy** [comment]
What version of openapi are you using?

**Comment by ben-moo** [comment]
Hi @samchungy,
Excellent spot. I'd accidentally set the `openapi` field to `3.0.0`.
Thank you for responding so quickly! I'll close this issue.
