### ISSUE TITLE
integrating with nestjs-zod

### ISSUE THREAD

**Issue by mohrazzak** [samchungy/zod-openapi#173]
It is important because we are using that to swagger our fields

**Comment by samchungy** [comment]
I'm not entirely sure what you mean here, if you're using it already to swagger your field why don't you use it to generate openapi doc?

**Comment by mohrazzak** [comment]
Because when i use 
iAmFile: z.string().openapi({type:'string', format:'binary'}); 
This is not showing as a file 
Check this 
https://stackoverflow.com/questions/77287011/nestjs-swagger-multipart-file-upload-issue-with-zod

**Comment by samchungy** [comment]
If you're gonna use either of our libraries you gotta use our respective createDocument functions. You can't use the nestjs one as they won't support the .openapi method

**Comment by samchungy** [comment]
Going to close this, please reopen if you still have issues
