### ISSUE TITLE
integration with trpc / trpc-openapi?

### ISSUE THREAD

**Issue by tonyxiao** [samchungy/zod-openapi#181]
Would love to use this library to generate solid openAPI spec. However we are currently using trpc and would love a solution to not have to duplicate the definition of routes.

**Comment by samchungy** [comment]
I mean I'm happy for them to use this library, and I'm also happy to build stuff if they need but it'll likely be more then using this library than the other way around

**Comment by tonyxiao** [comment]
Fair enough. Though to be trpc-openapi feels very much not maintained recently and I wonder if we should just build a new version on top of zod-openapi.

**Comment by samchungy** [comment]
Since trpc is outside of the scope of this project, I don't think I'd build it explicitly in here

**Comment by tonyxiao** [comment]
Makes sense. What server library to you personally use to complement zod-openapi?

**Comment by samchungy** [comment]
> Makes sense. What server library to you personally use to complement zod-openapi?

At the moment koa for work, but I've been trying to shift the workload to fastfy

**Comment by baptisteArno** [comment]
I'm exploring this at the moment I might create a fork of trpc-openapi that uses this library.

**Comment by tonyxiao** [comment]
@baptisteArno that'd be amazing. let me know if i can help in someway.

**Comment by samchungy** [comment]
> I'm exploring this at the moment I might create a fork of trpc-openapi that uses this library.

Let me know if I need to expose more internals

**Comment by LilyRose2798** [comment]
I've just pushed out a version on my fork of trpc-openapi with working zod-openapi integration if any of you here are interested:
https://github.com/LilyRose2798/trpc-openapi

**Comment by baptisteArno** [comment]
Amazing work, will try it out soon 🎉

**Comment by LilyRose2798** [comment]
Just published it now at https://www.npmjs.com/package/@lilyrose2798/trpc-openapi

**Comment by samchungy** [comment]
Okay I'm going to close this issue in here for now. Please re-open or raise another issue if you want extra integration help 🫡

**Comment by tonyxiao** [comment]
Finally got a chance to try it out. @LilyRose2798 works like a charm!
