### ISSUE TITLE
Opt into oneOf for union types

### ISSUE THREAD

**Issue by fmmoret** [samchungy/zod-openapi#183]
Some unions don't have a dedicated discriminator field and instead have totally noncompatible shapes
String | some object | some unambiguously different object shape.

Could we unsafely opt into / assert oneOf instead of anyOf? Many openapi generators that we've been using have very poor support or very poor impls for anyOf.

I don't have control over the my api payload shape and can't retroactively add discriminators.

**Comment by samchungy** [comment]
I suppose we could add a metadata override field for this: Something like `overrideUnionAnyOf?: true` or `unionOneOf: true`? Happy to take suggestions for names

**Comment by samchungy** [comment]
Easy I'll pop in a fix this weekend when I have a bit of time. Busy week 😪
