### ISSUE TITLE
“nullable” reference objects are not correctly generated.

### ISSUE THREAD

**Issue by mbsanchez** [samchungy/zod-openapi#186]
The issue is that when I have a type like this:

```javascript
const personSchema = z.object({
   firstname: z.string(),
   lastname: z.string()
});

const houseSchema = object({
   address: z.string(),
   owner: personSchema.nullable().optional()
});
```

When the open API spec is generated the owner field is generated like:
```
"owner": {
  "oneOf": [
    {
      "$ref": "#/components/schemas/Person"
    },
    {
      "nullable": true
    }
  ]
},
```

But it is incorrect, as when the client uses the spect to generate the typescript code, the owner field is not well recognized. The correct output should be:
```
"owner": {
  "oneOf": [
    {
      "$ref": "#/components/schemas/Person"
    },
  ],
  "nullable": true
},
```

**Comment by samchungy** [comment]
Ah nice one.

TIL: https://github.com/OAI/OpenAPI-Specification/issues/1368

I'll raise a PR sometime todayish

**Comment by mbsanchez** [comment]
Great, thank you so much,

FYI: in my case, this format I've shown you works perfectly using "anyOf", "oneOf" and "allOf". Check this screenshot of the [swagger](https://editor-next.swagger.io/) editor using "anyOf":

<img width="1350" alt="image" src="https://github.com/samchungy/zod-openapi/assets/143726/b9b4f0ba-a064-4d99-9e84-c64ca6e03422">
