### ISSUE TITLE
`effectType` does not fix the Unknown schema ZodEffects error

### ISSUE THREAD

**Issue by baptisteArno** [samchungy/zod-openapi#194]
I'm probably doing something wrong but I can't fix the `Unknown schema ZodEffects` error even though I'm adding the `effectType` as `output`

Reproduction: https://stackblitz.com/edit/node-typescript-playground-x6gywv?file=src%2Findex.ts

**Comment by samchungy** [comment]
Hmmm no that looks correct. I'll take a peek in an hour or two

**Comment by samchungy** [comment]
Ah no I see what's gone wrong there. Unfortunately because we can't hook into the ts compiler at runtime, we can't actually determine the type after the transform so you'll have to set the effectType to input in this case. So it uses the z.string() type.

**Comment by baptisteArno** [comment]
Indeed! Thanks for the heads up.

It maybe worth improving the error message if possible then :)
