### ISSUE TITLE
Support for ZodUndefined type

### ISSUE THREAD

**Issue by baptisteArno** [samchungy/zod-openapi#195]
I'm wondering if that would be possible to support the `ZodUndefined` type? I would expect to just ignore the field when generating the OpenAPI schema.

**Comment by baptisteArno** [comment]
To provide more context, I have a lot of `discriminatedUnion` where the discriminant can indeed be `undefined`. So I need to add `z.undefined()` to that field instead of just omitting it. Otherwise the discriminatedUnion throws an error.

**Comment by baptisteArno** [comment]
Also, I guess `ZodNever` type could behave the same way

**Comment by baptisteArno** [comment]
I would expect `ZodUndefined` and `ZodNever` fields to just be ignored and not included in the openapi document. Do you aggree with this? How feasible is it?

> Has zod fixed the support for that yet? I recall it not working properly

No, they event planning on deprecating the `discriminatedUnion` function in favor of a more flexible `switch` function. But that's out of this issue's scope :)

**Comment by samchungy** [comment]
That sounds reasonable to me. Should be relatively easy to implement
