### ISSUE TITLE
`.partial()` causes weird `allOf` with `description`

### ISSUE THREAD

**Issue by jaens** [samchungy/zod-openapi#209]
Example:

```js
const someField = z.string().describe("Some Field").openapi({ref: "someFieldRef"});

const obj = z.object({
   someField
}).partial();
```

Now, outputting this will cause a duplication of the `description` field in the `obj` schema (besides being in `components`):

```yaml
someField:
  allOf:
    - $ref: "#/components/schemas/someFieldRef"
    - description: Some Field
```

This is caused by `createNewSchema()`:

https://github.com/samchungy/zod-openapi/blob/794c9dcb59388050081c13d4c1fb5d6b55588d22/src/create/schema/index.ts#L63-L66

And that is called because `partial()` wraps every field in `ZodOptional`, causing the search for an existing ref in `createSchemaOrRef()` to fail, causing `enhanceWithMetadata()` to add that `allOf:`.

(of course, this also happens with bare `.optional()` on ref types, `.partial()` is just more likely to be used in this situation)

Now, other code of course (I assume `createOptionalSchema()`), removes that optional wrapper eventually, leaving the situation of something decorating itself...

Not sure what's the best way to solve this - possibly the "optional-removal" should take place before resolving refs, or `enhanceWithMetadata` should look "behind" refs to see if it's just duplicating what's already there. The former option seems cleaner since this is probably not the only weird edge case optionals cause.

**Comment by samchungy** [comment]
I'll take a squiz after work! :) Thanks for raising!

**Comment by samchungy** [comment]
I'll need to sleep on this one. I think it might require a little bit of refactor

**Comment by jaens** [comment]
Barely related observation: OpenAPI 3.1 permits adding `description` directly to `$ref`s, so the `allOf` from `enhanceMetadata()` would in *any* case be unnecessary (as long as it's only adding description), as this could just be expressed as `someField: { $ref: "#...", description: "Something" }`
