### ISSUE TITLE
Option `servers: [{ url: "v1" }]` conflicts with hono

### ISSUE THREAD

**Issue by hapaxlife** [samchungy/zod-openapi#219]
When adding option `servers: [{ url: "v1" }]`  openapi.json is correct but routes path are :
if I declare
- createRoute( /) then app.route("/hello", route)
- in hono http://localhost:8001/hello => correct to me
- in /openapi.json, /hello + server url v1
- http://localhost:8001/v1/hello in swagger ui => correct to me but v1/hello doesn't exist

if I declare
- createRoute( /) then app.route("/v1/hello", route)
- in hono http://localhost:8001/v1/hello => correct to me
- in /openapi.json, /v1/hello + server url v1 => add extra v1 => i don't want it
- http://localhost:8001/v1/v1/hello in swagger ui => correct but not expected due to path with v1

What is the best way to manage version ? Is it at zod openapi or code design with hono ?

**Comment by samchungy** [comment]
This seems more of a general openapi question:

With versioning you'd typically create a new path did the version:

Eg. 
```json
paths: {
    '/v1/jobs/{Job}': {
```

You wouldn't typically mess with the server url
