### ISSUE TITLE
How to extend imported zod objects (from another package)

### ISSUE THREAD

**Issue by zoiman** [samchungy/zod-openapi#224]
I have the following usecase. I am using zod schemas which are imported from other packages and then changed using `extend` or `omit`. Those schemas should be used as request and response schemas for openAPI.

How can I use `extendZodWithOpenApi` on those schemas without changing the original source schema?

Is this even possible?

**Comment by zoiman** [comment]
well in my case I had to change it in the imported packages.

**Comment by timzolleis** [comment]
Yeah, true - so you did the extension in your package and then added .openApi to your schemas? Because just extending zod does not do the job here...

**Comment by zoiman** [comment]
yes so it works nicely here but lets say you have a user schema from another package you need to add a `openapi()` there to get all the members. In my case I did this:

```typsescript
// from @somecompany/....
export const USER_SCHEMA =  z.stirctObject({
name: z.string(),
....
}).openapi({"this is the user schema"});

// in your code

import {USER_SCHEMA} from ...

export const MYUSER_SCHEMA = USER_SCHEMA.extend({
someNewAttr: z.string(),
}).openapi({"some descriptions"});
```

this worked quite well and all attributes where in the openapi specs.

**Comment by timzolleis** [comment]
Nice, thanks a lot!
