### ISSUE TITLE
ZodIntersection/ZodDiscriminatedUnion in request parameters

### ISSUE THREAD

**Issue by adjsky** [samchungy/zod-openapi#232]
Hi! While integrating the library, I found that `failed to find ZodObject in schema` exception is thrown if you use `ZodIntersection` or `ZodDiscriminatedUnion` schemas for request parameters.

As I understand it, `ZodIntersection` or `ZodDiscriminatedUnion` are not supported for generating request parameters. But, if you use a custom type as indicated in the documentation: `.openapi({ type: ... })`, the error is still thrown.

Example code:
```ts
import { z } from "zod";
import { createDocument, extendZodWithOpenApi } from "zod-openapi";

extendZodWithOpenApi(z);

createDocument({
  openapi: "3.1.0",
  info: {
    title: "My API",
    version: "1.0.0",
  },
  paths: {
    "/test": {
      get: {
        requestParams: {
          header: z.discriminatedUnion("key", [
            z.object({ key: z.literal(true) }),
          ]),
          query: z.object({}).and(z.object({})),
          path: z.object({}).and(z.object({})).openapi({ type: "string" }),
        },
        responses: {
          "200": {
            description: "200 OK",
          },
        },
      },
    },
  },
});
```

I can get around using `.merge`/`.extend` instead of `.and`, but I don't know how to make it work with `.discriminatedUnion`. Is there a way?

**Comment by samchungy** [comment]
Hey there thanks for the issue, I don't believe openapi supports unions or discriminated unions for parameters, but I'm happy to be corrected if you can link me an example?

**Comment by samchungy** [comment]
Closing for now, please reopen if you still have an issue
