### ISSUE TITLE
How do I group my requests by entity?

### ISSUE THREAD

**Issue by gcmonteiro02** [samchungy/zod-openapi#269]
My requests are grouped together with the title `“default”`. I'd like to know how I can use the lib to group them by entity, for example “campaigns” and “users”, and for each entity to have a set of get, post and other requests...

![image](https://github.com/samchungy/zod-openapi/assets/17880671/893887b5-d30b-410c-9347-076b1763f523)

**Comment by samchungy** [comment]
You'll want to use tags: https://swagger.io/docs/specification/grouping-operations-with-tags/
