### ISSUE TITLE
Parameter `type` is still required even when `anyOf` is specified.

### ISSUE THREAD

**Issue by jeremyjacob** [samchungy/zod-openapi#274]
When manually defining an OpenAPI type with `.openapi({...})`, the `type` key is required, even when `anyOf` is specified in supplement of `type`. This might be an issue with OpenAPI 3.1 specifically.

Thank you for your work on this handy library.

**Comment by samchungy** [comment]
Hey thanks for raising the issue! That's a good point that we should also allow specifying `anyOf`, `oneOf` and possibly `allOf` as overrides.

Any chance you can share what you're trying to represent to see if there's an alternative in the meantime?

**Comment by jeremyjacob** [comment]
I'd be happy to share. I have a recursive schema (let's say Order -> Customer -> Order[] -> etc). Because zod-openapi needs manual annotations (I think) for `z.lazy()`, I'm adding them like this:

```ts
const baseOrder = z.object({...})

const customerFieldSchema = () => z.string().or(Customer).nullable().openapi({ "x-expandable": true, description: "Expandable" });

export const Order: ZodCompositeType<
	typeof baseOrder,
	{ customer: ReturnType<typeof customerFieldSchema> }
> = baseOrder
	.extend({
		customer: z
			.lazy(customerFieldSchema)
			.openapi({
				anyOf: [
					{ type: "string" },
					{ $ref: `#/components/schemas/Customer` },
				],
				type: "placeholder" as "object", // then the `type` key is removed by a post-processing step
			}),
	})
	.strict()
	.openapi("Order");
```

The workaround in place now is just to include a type key and remove it later in middleware or post-processing. Maybe there's a better way to do this to absolve the need for the manual annotation?

**Comment by samchungy** [comment]
Can I check if you're using zod-to-openapi or this library because the .openapi("Order") is from that library.

We use .openapi({ ref: "Order" }).

If you assign a ref to the Customer schema it should all work as we do support lazy 🙂

**Comment by jeremyjacob** [comment]
I see! I was using it through the Hono adapter and must have mixed up the libraries. I'll open an issue over at zod-to-openapi.

I'll see about using this library instead in the meantime. Thanks a bunch and sorry for the confusion.
