### ISSUE TITLE
Default string format setting for ZodDate

### ISSUE THREAD

**Issue by mdoi2** [samchungy/zod-openapi#305]
Thanks for creating a nice library😄

When converting a ZodDate to an openapi schema, the type is a string, and the format is unset and fixed.
However, regarding format, if there is one format that works best for one project, it would be somewhat redundant to set the format with the openapi function every time.

So what do you think about allowing pre-set default values for this format?
If this is a good suggestion, I would like to figure out how to modify it.

**Comment by samchungy** [comment]
Hey there, you should be able to set it by using `.openapi()` if need be. Not sure if we can make assumptions about that one as there are a few different ones we could input.

```ts
z.date().openapi( { format: 'date-time' })
```

**Comment by mdoi2** [comment]
Thank you for replying!

Yes, I have already implemented that.

In most cases, I think the values set for this format are these three patterns.
- [unset]
- date-time
- date

Of these, I personally would like the `date-time` to be the default the most.
Because in many cases when a Javascript Date is serialized, it will be in the `date-time` format.

However, this ideal may be unique to me, as it is currently [unset], and may vary from project to project.

So I thought that having a default value that can be set in advance, and only overriding it with the openapi function if it needs to be changed, might be a good way for someone with similar ideas as mine.
