### ISSUE TITLE
Supporting Multiple Property Level Examples

### ISSUE THREAD

**Issue by cleo-wvuf** [samchungy/zod-openapi#329]
Hello.

I am using open api 3.1.0 and it looks like this should be supported.

I am using an object that looks like:

`z.object({
 GoalAmount: z.number().openapi({
        description: "The goal for this unit.",
        examples: [50000000000, 983981]
    }).nullable()
`

but when i look at the generated schema it shows up as
 
`"GoalAmount": {
                        "type": [
                          "number",
                          "null"
                        ],
                        "description": "The goal for this unit.",
                        "example": 50000000000
                      },`
                      
As you can see it is only generating 1 example.

As a side note, how would you show that a valid value would be null? Thanks.

**Comment by samchungy** [comment]
Can you give an example of your usage? We don't do any transformations on the examples field so I can't see why it wouldn't be working

**Comment by cleo-wvuf** [comment]
Ah, my apologies. I believe I meant to make this issue on fastify-zod-openapi repo. It appears to be an issue with the transform in

`... 
transform: fastifyZodOpenApiTransform,
transformObject: fastifyZodOpenApiTransformObject,`

I will close this and reopen there. Sorry about that.

**Comment by samchungy** [comment]
To prevent you from wasting your time @cleo-wvuf , you'll need to raise an issue with fastify/swagger. Their logic trims the array:

https://github.com/fastify/fastify-swagger/blob/1de673f8de777ab63711a0f1b2c062b2e2df8316/lib/spec/openapi/utils.js#L220
