### ISSUE TITLE
requestBody schema is being turned into a _def

### ISSUE THREAD

**Issue by Soviut** [samchungy/zod-openapi#354]
I'm using hono to build an API and it has a `@hono/zod-openapi` package that acts as a thin wrapper around zod-openapi.

I have reported this bug on that project here https://github.com/honojs/hono/issues/3594 but think this could be an upstream issue so I'm cross-posting.

Basically, giving a Zod object to the `requestBody` schema is causing it to be converted to a `_def` for some reason.

It throws this error in VSCode

![image](https://github.com/user-attachments/assets/fdcf20e1-a612-46fc-a40c-473cc1070348)

and produces this JSON doc (note the `_def`)

```json
"/webhooks/applications/update": {
  "post": {
    "description": "Webhook handler for application updates from Ashby",
    "requestBody": {
      "content": {
        "application/json": {
          "schema": {
            "_def": {
              "unknownKeys": "strip",
              "catchall": {
                "_def": {
                  "typeName": "ZodNever"
                }
              },
              "typeName": "ZodObject"
            },
            "_cached": null
          }
        }
      }
    },
// etc...
```

**Comment by samchungy** [comment]
Hey you'll have to go to https://github.com/asteasolutions/zod-to-openapi as they wrap this library and not this one
