### ISSUE TITLE
Multiple Ref Support

### ISSUE THREAD

**Issue by Luceium** [samchungy/zod-openapi#357]
I'm trying to create a schema using multiple refs.
I tried using `createSchema(zodType, ops?)` and auto registering refs with `.openapi({ref: "name"})`

Despite `CreateSchemaOptions` including a `components` field, it seems to be singular.
```typescript
interface CreateSchemaOptions extends CreateDocumentOptions {
    /**
     * This controls whether this should be rendered as a request (`input`) or response (`output`). Defaults to `output`
     */
    schemaType?: CreationType;
    /**
     * OpenAPI version to use, defaults to `'3.1.0'`
     */
    openapi?: OpenApiVersion;
    /**
     * Additional components to use and create while rendering the schema
     */
    components?: Record<string, ZodType>; // SEE HERE: A record that takes in only 1 component
    /**
     * The $ref path to use for the component. Defaults to `#/components/schemas/`
     */
    componentRefPath?: string;
}
```

When using auto generated refs the output disincludes the implementation of all registered components (expected behaviour) but only includes the definition of the first ref (unexpected behaviour)

Example:
```typescript
const A = z.string().openapi({ref: "A"})
const B = z.number().int().openapi({ref: "B"})
const C = z.object({
  a: A,
  b: B.openapi({describe: "B should be a ref too"}),
}).openapi({title: "C"})

const { schema, components } = generateSchema(C);
console.log(schema)
console.log(components)
```

Expected Output:
Schema:
```
{
  type: 'object',
  properties: {
    a: { '$ref': '#/components/schemas/A' },
    b: { '$ref': '#/components/schemas/B' ,}
  },
  required: [ 'a', 'b' ],
  title: 'C'
}
```
Components:
```
{
  A: { type: 'string', enum: [ '1', '2', '3' ] },
  B: { type: 'integer' }
}
```

Actual Output:
Schema:
```
{
  type: 'object',
  properties: {
    a: { '$ref': '#/components/schemas/A' },
    b: { type: 'integer', description: 'B should be a ref too' }
  },
  required: [ 'a', 'b' ],
  title: 'C'
}
```
Components:
`{ A: { type: 'string', enum: [ '1', '2', '3' ] } }`

**Comment by Luceium** [comment]
As I wrote the example script I realized that I was able to get multiple refs until I had an `.openapi()` on the ref. I realize this is similar to an existing bug #303. One concern for my application is that I want to control where the description goes.
So instead of the description being a part of the component definition in `components` I want it to show up in `schema`.

Using zod's `refine` seems to work.

Here's the updated code:
```typescript
const A = z.string().openapi({ref: "A"})
const B = z.number().int().openapi({ref: "B"})
const C = z.object({
  a: A,
  b: B.refine((value) => true).openapi({describe: "B should be a ref too"}),
}).openapi({title: "C"})

const { schema, components } = generateSchema(C);
console.log(schema)
console.log(components)
```

**Comment by samchungy** [comment]
Hey thanks for raising! I think it'll be covered by https://github.com/samchungy/zod-openapi/pull/356 when I release 🙂
