### ISSUE TITLE
`allOf` through z.extend with refs / union actually `anyOf`

### ISSUE THREAD

**Issue by jakobfenerparc** [samchungy/zod-openapi#365]
Hi Sam,

amazing library, happy to see something being to actively developed.
More a question since it's not clear from the README documentation.

In the documentation it says that a z.union translates into `allOf` (unless globally configured to `oneOf` through the `unionOneOf` setting).
I think this should be changed to `anyOf` as the code suggests.

My actual question:
In my case I need to (for compatability reasons) create an `allOf` schema, which consists of multiple refs and some custom type.
```yaml
    MySchema:
      allOf:
        - $ref: "#/components/schemas/Base1"
        - $ref: "#/components/schemas/Base2"
        - type: object
          required:
            - prop1
          properties:
            prop1:
              type: string
              description: Description1
```

I tried to get this by using extend as mentioned in the docs.
But the multiple refs are a problem, because when doing this:

```typescript
const Base1 = z.object({ a: z.string(), b: z.number() }).openapi({ ref: "Base1" });
const Base2 = z.object({ c: z.string() }).openapi({ ref: "Base2" });
const MySchema = Base1.extend(Base2.shape).extend(z.object({ prop1: z.string() }))
```

I get a ref for `Base1`, but since `.shape` flattens `Base2` the openapi information gets lost, so `Base2` and the last `z.object` get merged inline into `MySchema`.

Is there a different way of constructing the openapi schema above (with the allOf refs) that I did not see?

**Comment by samchungy** [comment]
Ah yep you caught a mistake, I'll get onto fixing it.

Hmmm yeah that's tricky, unfortunately yeah passing in the shape means we can't infer where it came from.

https://github.com/samchungy/zod-openapi/pull/360

You could potentially use `.and()`?

**Comment by jakobfenerparc** [comment]
`z.and` works just right, thanks.
Apart from the docs, this issue solved I guess.

Thanks for !instant feedback!
