### ISSUE TITLE
`.omit()` and `.openapi({ ref: ... })` Produce Incorrect OpenAPI Schema

### ISSUE THREAD

**Issue by kennyjwilli** [samchungy/zod-openapi#382]
When using `.openapi({ ref: ... })`, I expect the generated schema to respect the `.omit()` modifier. However, the resulting schema incorrectly references the base schema, ignoring the omitted keys.

## Expected Behavior

Using `.omit()` with `.openapi({ ref: ... })` should generate an OpenAPI schema that respects the omitted keys. For example, the `OmitBaseSchema` schema should reflect the modified structure (excluding `key2`) in the OpenAPI document.

## Actual Behavior

The generated schema for `OmitBaseSchema` does not account for the `.omit()` operation. Instead, it points to `BaseSchema` directly, resulting in an incorrect OpenAPI specification. The omitted keys are still present in the referenced schema.

## Repro

```typescript
const baseSchema = z
  .object({
    key1: z.string(),
    key2: z.string(),
  })
  .openapi({ ref: 'BaseSchema' });

const omitBaseSchema = baseSchema.omit({ key2: true }).openapi({ ref: 'OmitBaseSchema' });

const document = createDocument({
  openapi: '3.1.0',
  info: {
    title: 'My API',
    version: '1.0.0',
  },
  paths: {
    '/jobs': {
      put: {
        requestBody: {
          content: {
            'application/json': { schema: omitBaseSchema },
          },
        },
        responses: {
          '200': {
            description: '200 OK',
            content: {
              'application/json': { schema: z.object({}) },
            },
          },
        },
      },
    },
  },
}); 
```

### Observed Output

The resulting `document` looks like this:

```typescript
{
  openapi: '3.1.0',
  info: { title: 'My API', version: '1.0.0' },
  paths: {
    '/jobs': {
      put: {
        requestBody: {
          content: {
            'application/json': {
              schema: { '$ref': '#/components/schemas/OmitBaseSchema' }
            }
          }
        },
        responses: {
          '200': {
            description: '200 OK',
            content: { 'application/json': { schema: { type: 'object' } } }
          }
        }
      }
    }
  },
  components: {
    schemas: {
      BaseSchema: {
        type: 'object',
        properties: { key1: { type: 'string' }, key2: { type: 'string' } },
        required: [ 'key1', 'key2' ]
      },
      OmitBaseSchema: { '$ref': '#/components/schemas/BaseSchema' }
    }
  }
}
```

Note that `OmitBaseSchema` incorrectly references `BaseSchema`, ignoring the omission of `key2`.

### Expected Output

The `OmitBaseSchema` schema should look like this:

```typescript
components: {
  schemas: {
    BaseSchema: {
      type: 'object',
      properties: { key1: { type: 'string' }, key2: { type: 'string' } },
      required: ['key1', 'key2']
    },
    OmitBaseSchema: {
      type: 'object',
      properties: { key1: { type: 'string' } },
      required: ['key1']
    }
  }
}
```

## **Environment**

- **zod-openapi** version: 4.1.0

**Comment by samchungy** [comment]
Thanks for raising @kennyjwilli!

v4.1.2 should fix this

**Comment by kennyjwilli** [comment]
You're welcome. And thank you for the absolutely incredible turnaround time.
