### ISSUE TITLE
`unionOneOf` option does not work

### ISSUE THREAD

**Issue by Blade67** [samchungy/zod-openapi#391]
As the title suggest, the `unionOneOf` option does not properly replace `anyOf` with `oneOf`!
On that note, I'm fairly certain none of the options currently work.

**Comment by samchungy** [comment]
Hey there, can you please include a reproduction or example?

**Comment by Blade67** [comment]
I apologise for the delay.
The following union was used to test:
```ts
const mySchema = z.object({
    status: z.union([z.literal(300), z.literal(301)])
})
```
But even with the `unionOneOf` option enabled, the generated openapi config still uses `anyOf`.

**Comment by samchungy** [comment]
Hey, this is not a minimal reproducible. I cannot help you if you don't provide more information.
