### ISSUE TITLE
`.openapi()` does not exist when extending zod with `extendZodWithOpenApi`

### ISSUE THREAD

**Issue by mauricewegner** [samchungy/zod-openapi#397]
Since `4.2.1` (https://github.com/samchungy/zod-openapi/pull/393) the extended types are not being supplied when extending zod with `extendZodWithOpenApi`.

Downgrading to `4.2.0` fixes this issue.

**Comment by samchungy** [comment]
Hey, you might need to check if you have different versions of zod-openapi in your dependencies. Your lockfile is probably a good place to check.

Unfortunately this is a limitation of TypeScript which also affects the main Zod library when they release type changes

**Comment by samchungy** [comment]
Ah gotcha the manual extend is broken. 👀 Looing into it

**Comment by samchungy** [comment]
Thanks for raising @mauricewegner 🙏
