### ISSUE TITLE
avoid isOptional/isNullable

### ISSUE THREAD

**Issue by jedwards1211** [samchungy/zod-openapi#93]
Hey, we've been trying `zod-openapi` out, but we hit a snag where it uses `isOptional` because that basically tries to sync parse `undefined` and [throws on our schemas with async transforms](https://github.com/colinhacks/zod/issues/2456).

In that issue I filed with zod I suggested looking at the schema types instead of trying to sync parse, but they may want it to be able to tell if a schema with sync transforms/sync refinements accept undefined...

So in the meantime, how would you feel about a PR to do something like this instead?
```ts
function isOptional<T extends z.ZodTypeAny(schema: T): boolean {
  if (schema instanceof z.ZodOptional || schema instanceof z.ZodUndefined /* etc... */) return true;
  if (schema instanceof z.ZodUnion) return schema.options.some(isOptional);
  if (schema instanceof z.ZodIntersection) return isOptional(schema._def.left) && isOptional(schema._def.right);
  if (schema instanceof z.ZodNullable) return isOptional(schema._def.innerType);
  if (schema instanceof z.ZodLazy) return isOptional(schema.schema);
  // etc...
}
```

**Comment by samchungy** [comment]
I'd be okay with this
